/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as access from "../access.js";
import type * as activity from "../activity.js";
import type * as agency from "../agency.js";
import type * as agencyBilling from "../agencyBilling.js";
import type * as agencyOps from "../agencyOps.js";
import type * as agencyPlans from "../agencyPlans.js";
import type * as agencyProfile from "../agencyProfile.js";
import type * as agencySettings from "../agencySettings.js";
import type * as agencyStaff from "../agencyStaff.js";
import type * as agent from "../agent.js";
import type * as agentAutomations from "../agentAutomations.js";
import type * as agentFleet from "../agentFleet.js";
import type * as agentHealth from "../agentHealth.js";
import type * as agentRules from "../agentRules.js";
import type * as agents_generators from "../agents/generators.js";
import type * as aiActions from "../aiActions.js";
import type * as aiArtifacts from "../aiArtifacts.js";
import type * as aiContext from "../aiContext.js";
import type * as arrivalPrep from "../arrivalPrep.js";
import type * as artists from "../artists.js";
import type * as assetDocuments from "../assetDocuments.js";
import type * as audit from "../audit.js";
import type * as automation from "../automation.js";
import type * as availability from "../availability.js";
import type * as benchmark from "../benchmark.js";
import type * as betaAccess from "../betaAccess.js";
import type * as betaClock from "../betaClock.js";
import type * as betaLicense from "../betaLicense.js";
import type * as billing from "../billing.js";
import type * as billingWebhooks from "../billingWebhooks.js";
import type * as booking from "../booking.js";
import type * as bookingFunnel from "../bookingFunnel.js";
import type * as brandHero from "../brandHero.js";
import type * as branding from "../branding.js";
import type * as cardOnFile from "../cardOnFile.js";
import type * as checklists from "../checklists.js";
import type * as clerkIdRemap from "../clerkIdRemap.js";
import type * as clientEmail from "../clientEmail.js";
import type * as contact from "../contact.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as dataRights from "../dataRights.js";
import type * as deliverables from "../deliverables.js";
import type * as demoMode from "../demoMode.js";
import type * as demoRefresh from "../demoRefresh.js";
import type * as directory from "../directory.js";
import type * as engineeringLogs from "../engineeringLogs.js";
import type * as equipment from "../equipment.js";
import type * as expenses from "../expenses.js";
import type * as exports from "../exports.js";
import type * as externalCalendars from "../externalCalendars.js";
import type * as externalCalendarsActions from "../externalCalendarsActions.js";
import type * as feeTemplates from "../feeTemplates.js";
import type * as files from "../files.js";
import type * as googleAuth from "../googleAuth.js";
import type * as googleCalendar from "../googleCalendar.js";
import type * as googleCalendarSync from "../googleCalendarSync.js";
import type * as grants from "../grants.js";
import type * as handover from "../handover.js";
import type * as http from "../http.js";
import type * as importClients from "../importClients.js";
import type * as insights from "../insights.js";
import type * as invites from "../invites.js";
import type * as invoicePay from "../invoicePay.js";
import type * as invoices from "../invoices.js";
import type * as lib_access from "../lib/access.js";
import type * as lib_accessPolicies from "../lib/accessPolicies.js";
import type * as lib_accessTypes from "../lib/accessTypes.js";
import type * as lib_aiGuard from "../lib/aiGuard.js";
import type * as lib_aiVerify from "../lib/aiVerify.js";
import type * as lib_betaNda from "../lib/betaNda.js";
import type * as lib_betaPlan from "../lib/betaPlan.js";
import type * as lib_billingGate from "../lib/billingGate.js";
import type * as lib_checklistTemplates from "../lib/checklistTemplates.js";
import type * as lib_clerkAllowlist from "../lib/clerkAllowlist.js";
import type * as lib_clerkErrors from "../lib/clerkErrors.js";
import type * as lib_comp from "../lib/comp.js";
import type * as lib_connectors from "../lib/connectors.js";
import type * as lib_deviceResearch from "../lib/deviceResearch.js";
import type * as lib_digestSchedule from "../lib/digestSchedule.js";
import type * as lib_email from "../lib/email.js";
import type * as lib_emailTemplates_activation from "../lib/emailTemplates/activation.js";
import type * as lib_emailTemplates_betaEnding from "../lib/emailTemplates/betaEnding.js";
import type * as lib_emailTemplates_betaInvite from "../lib/emailTemplates/betaInvite.js";
import type * as lib_emailTemplates_betaWelcome from "../lib/emailTemplates/betaWelcome.js";
import type * as lib_emailTemplates_invite from "../lib/emailTemplates/invite.js";
import type * as lib_emailTemplates_layout from "../lib/emailTemplates/layout.js";
import type * as lib_entitlements from "../lib/entitlements.js";
import type * as lib_gearCatalog from "../lib/gearCatalog.js";
import type * as lib_gearRental from "../lib/gearRental.js";
import type * as lib_google from "../lib/google.js";
import type * as lib_guardrails from "../lib/guardrails.js";
import type * as lib_holidays from "../lib/holidays.js";
import type * as lib_links from "../lib/links.js";
import type * as lib_managerBrain from "../lib/managerBrain.js";
import type * as lib_modules from "../lib/modules.js";
import type * as lib_money from "../lib/money.js";
import type * as lib_musicLink from "../lib/musicLink.js";
import type * as lib_notify from "../lib/notify.js";
import type * as lib_openai from "../lib/openai.js";
import type * as lib_patchValidators from "../lib/patchValidators.js";
import type * as lib_payoutMath from "../lib/payoutMath.js";
import type * as lib_payroll from "../lib/payroll.js";
import type * as lib_phone from "../lib/phone.js";
import type * as lib_plans from "../lib/plans.js";
import type * as lib_pnl from "../lib/pnl.js";
import type * as lib_portTemplates from "../lib/portTemplates.js";
import type * as lib_redact from "../lib/redact.js";
import type * as lib_roadmap from "../lib/roadmap.js";
import type * as lib_roomStatus from "../lib/roomStatus.js";
import type * as lib_ruleSpec from "../lib/ruleSpec.js";
import type * as lib_sms from "../lib/sms.js";
import type * as lib_smsKeywords from "../lib/smsKeywords.js";
import type * as lib_smsTemplates from "../lib/smsTemplates.js";
import type * as lib_softwareCatalog from "../lib/softwareCatalog.js";
import type * as lib_specLookup from "../lib/specLookup.js";
import type * as lib_starter from "../lib/starter.js";
import type * as lib_stripe from "../lib/stripe.js";
import type * as lib_studioGraph from "../lib/studioGraph.js";
import type * as lib_studioKnowledge from "../lib/studioKnowledge.js";
import type * as lib_studioSite from "../lib/studioSite.js";
import type * as lib_t10 from "../lib/t10.js";
import type * as lib_tenant from "../lib/tenant.js";
import type * as lib_text from "../lib/text.js";
import type * as lib_themeSpec from "../lib/themeSpec.js";
import type * as lib_tier from "../lib/tier.js";
import type * as lib_tz from "../lib/tz.js";
import type * as lib_usTaxRates from "../lib/usTaxRates.js";
import type * as licensing from "../licensing.js";
import type * as maintenance from "../maintenance.js";
import type * as members from "../members.js";
import type * as memberships from "../memberships.js";
import type * as migrations from "../migrations.js";
import type * as migrations_dashes from "../migrations_dashes.js";
import type * as modules from "../modules.js";
import type * as notifications from "../notifications.js";
import type * as onboarding from "../onboarding.js";
import type * as opportunities from "../opportunities.js";
import type * as opsActions from "../opsActions.js";
import type * as opsBrain from "../opsBrain.js";
import type * as orgs from "../orgs.js";
import type * as packages from "../packages.js";
import type * as patchCables from "../patchCables.js";
import type * as patchManager from "../patchManager.js";
import type * as patchSpecs from "../patchSpecs.js";
import type * as payments from "../payments.js";
import type * as payouts from "../payouts.js";
import type * as payroll from "../payroll.js";
import type * as portal from "../portal.js";
import type * as predictions from "../predictions.js";
import type * as profitability from "../profitability.js";
import type * as push from "../push.js";
import type * as pushAlerts from "../pushAlerts.js";
import type * as pushSend from "../pushSend.js";
import type * as receptionist from "../receptionist.js";
import type * as recovery from "../recovery.js";
import type * as recoveryRecap from "../recoveryRecap.js";
import type * as releases from "../releases.js";
import type * as reminders from "../reminders.js";
import type * as reports from "../reports.js";
import type * as reviews from "../reviews.js";
import type * as rightsExport from "../rightsExport.js";
import type * as risk from "../risk.js";
import type * as rooms from "../rooms.js";
import type * as seed from "../seed.js";
import type * as seedDemoFinance from "../seedDemoFinance.js";
import type * as seedDemoFurniture from "../seedDemoFurniture.js";
import type * as seedDemoPatch from "../seedDemoPatch.js";
import type * as seedDemoSoftware from "../seedDemoSoftware.js";
import type * as seedDemoYear from "../seedDemoYear.js";
import type * as seedSchedule from "../seedSchedule.js";
import type * as sessions from "../sessions.js";
import type * as shifts from "../shifts.js";
import type * as sms from "../sms.js";
import type * as smsFlows from "../smsFlows.js";
import type * as smsTestFixtures from "../smsTestFixtures.js";
import type * as software from "../software.js";
import type * as songImport from "../songImport.js";
import type * as songs from "../songs.js";
import type * as splitSheets from "../splitSheets.js";
import type * as splitSignatures from "../splitSignatures.js";
import type * as stageDemo from "../stageDemo.js";
import type * as stripeConnect from "../stripeConnect.js";
import type * as studioBrain from "../studioBrain.js";
import type * as studioImport from "../studioImport.js";
import type * as studioManager from "../studioManager.js";
import type * as subaccountDeletion from "../subaccountDeletion.js";
import type * as testHarness from "../testHarness.js";
import type * as theme from "../theme.js";
import type * as timeclock from "../timeclock.js";
import type * as today from "../today.js";
import type * as twilioA2P from "../twilioA2P.js";
import type * as usage from "../usage.js";
import type * as visitors from "../visitors.js";
import type * as waitlist from "../waitlist.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  access: typeof access;
  activity: typeof activity;
  agency: typeof agency;
  agencyBilling: typeof agencyBilling;
  agencyOps: typeof agencyOps;
  agencyPlans: typeof agencyPlans;
  agencyProfile: typeof agencyProfile;
  agencySettings: typeof agencySettings;
  agencyStaff: typeof agencyStaff;
  agent: typeof agent;
  agentAutomations: typeof agentAutomations;
  agentFleet: typeof agentFleet;
  agentHealth: typeof agentHealth;
  agentRules: typeof agentRules;
  "agents/generators": typeof agents_generators;
  aiActions: typeof aiActions;
  aiArtifacts: typeof aiArtifacts;
  aiContext: typeof aiContext;
  arrivalPrep: typeof arrivalPrep;
  artists: typeof artists;
  assetDocuments: typeof assetDocuments;
  audit: typeof audit;
  automation: typeof automation;
  availability: typeof availability;
  benchmark: typeof benchmark;
  betaAccess: typeof betaAccess;
  betaClock: typeof betaClock;
  betaLicense: typeof betaLicense;
  billing: typeof billing;
  billingWebhooks: typeof billingWebhooks;
  booking: typeof booking;
  bookingFunnel: typeof bookingFunnel;
  brandHero: typeof brandHero;
  branding: typeof branding;
  cardOnFile: typeof cardOnFile;
  checklists: typeof checklists;
  clerkIdRemap: typeof clerkIdRemap;
  clientEmail: typeof clientEmail;
  contact: typeof contact;
  crons: typeof crons;
  dashboard: typeof dashboard;
  dataRights: typeof dataRights;
  deliverables: typeof deliverables;
  demoMode: typeof demoMode;
  demoRefresh: typeof demoRefresh;
  directory: typeof directory;
  engineeringLogs: typeof engineeringLogs;
  equipment: typeof equipment;
  expenses: typeof expenses;
  exports: typeof exports;
  externalCalendars: typeof externalCalendars;
  externalCalendarsActions: typeof externalCalendarsActions;
  feeTemplates: typeof feeTemplates;
  files: typeof files;
  googleAuth: typeof googleAuth;
  googleCalendar: typeof googleCalendar;
  googleCalendarSync: typeof googleCalendarSync;
  grants: typeof grants;
  handover: typeof handover;
  http: typeof http;
  importClients: typeof importClients;
  insights: typeof insights;
  invites: typeof invites;
  invoicePay: typeof invoicePay;
  invoices: typeof invoices;
  "lib/access": typeof lib_access;
  "lib/accessPolicies": typeof lib_accessPolicies;
  "lib/accessTypes": typeof lib_accessTypes;
  "lib/aiGuard": typeof lib_aiGuard;
  "lib/aiVerify": typeof lib_aiVerify;
  "lib/betaNda": typeof lib_betaNda;
  "lib/betaPlan": typeof lib_betaPlan;
  "lib/billingGate": typeof lib_billingGate;
  "lib/checklistTemplates": typeof lib_checklistTemplates;
  "lib/clerkAllowlist": typeof lib_clerkAllowlist;
  "lib/clerkErrors": typeof lib_clerkErrors;
  "lib/comp": typeof lib_comp;
  "lib/connectors": typeof lib_connectors;
  "lib/deviceResearch": typeof lib_deviceResearch;
  "lib/digestSchedule": typeof lib_digestSchedule;
  "lib/email": typeof lib_email;
  "lib/emailTemplates/activation": typeof lib_emailTemplates_activation;
  "lib/emailTemplates/betaEnding": typeof lib_emailTemplates_betaEnding;
  "lib/emailTemplates/betaInvite": typeof lib_emailTemplates_betaInvite;
  "lib/emailTemplates/betaWelcome": typeof lib_emailTemplates_betaWelcome;
  "lib/emailTemplates/invite": typeof lib_emailTemplates_invite;
  "lib/emailTemplates/layout": typeof lib_emailTemplates_layout;
  "lib/entitlements": typeof lib_entitlements;
  "lib/gearCatalog": typeof lib_gearCatalog;
  "lib/gearRental": typeof lib_gearRental;
  "lib/google": typeof lib_google;
  "lib/guardrails": typeof lib_guardrails;
  "lib/holidays": typeof lib_holidays;
  "lib/links": typeof lib_links;
  "lib/managerBrain": typeof lib_managerBrain;
  "lib/modules": typeof lib_modules;
  "lib/money": typeof lib_money;
  "lib/musicLink": typeof lib_musicLink;
  "lib/notify": typeof lib_notify;
  "lib/openai": typeof lib_openai;
  "lib/patchValidators": typeof lib_patchValidators;
  "lib/payoutMath": typeof lib_payoutMath;
  "lib/payroll": typeof lib_payroll;
  "lib/phone": typeof lib_phone;
  "lib/plans": typeof lib_plans;
  "lib/pnl": typeof lib_pnl;
  "lib/portTemplates": typeof lib_portTemplates;
  "lib/redact": typeof lib_redact;
  "lib/roadmap": typeof lib_roadmap;
  "lib/roomStatus": typeof lib_roomStatus;
  "lib/ruleSpec": typeof lib_ruleSpec;
  "lib/sms": typeof lib_sms;
  "lib/smsKeywords": typeof lib_smsKeywords;
  "lib/smsTemplates": typeof lib_smsTemplates;
  "lib/softwareCatalog": typeof lib_softwareCatalog;
  "lib/specLookup": typeof lib_specLookup;
  "lib/starter": typeof lib_starter;
  "lib/stripe": typeof lib_stripe;
  "lib/studioGraph": typeof lib_studioGraph;
  "lib/studioKnowledge": typeof lib_studioKnowledge;
  "lib/studioSite": typeof lib_studioSite;
  "lib/t10": typeof lib_t10;
  "lib/tenant": typeof lib_tenant;
  "lib/text": typeof lib_text;
  "lib/themeSpec": typeof lib_themeSpec;
  "lib/tier": typeof lib_tier;
  "lib/tz": typeof lib_tz;
  "lib/usTaxRates": typeof lib_usTaxRates;
  licensing: typeof licensing;
  maintenance: typeof maintenance;
  members: typeof members;
  memberships: typeof memberships;
  migrations: typeof migrations;
  migrations_dashes: typeof migrations_dashes;
  modules: typeof modules;
  notifications: typeof notifications;
  onboarding: typeof onboarding;
  opportunities: typeof opportunities;
  opsActions: typeof opsActions;
  opsBrain: typeof opsBrain;
  orgs: typeof orgs;
  packages: typeof packages;
  patchCables: typeof patchCables;
  patchManager: typeof patchManager;
  patchSpecs: typeof patchSpecs;
  payments: typeof payments;
  payouts: typeof payouts;
  payroll: typeof payroll;
  portal: typeof portal;
  predictions: typeof predictions;
  profitability: typeof profitability;
  push: typeof push;
  pushAlerts: typeof pushAlerts;
  pushSend: typeof pushSend;
  receptionist: typeof receptionist;
  recovery: typeof recovery;
  recoveryRecap: typeof recoveryRecap;
  releases: typeof releases;
  reminders: typeof reminders;
  reports: typeof reports;
  reviews: typeof reviews;
  rightsExport: typeof rightsExport;
  risk: typeof risk;
  rooms: typeof rooms;
  seed: typeof seed;
  seedDemoFinance: typeof seedDemoFinance;
  seedDemoFurniture: typeof seedDemoFurniture;
  seedDemoPatch: typeof seedDemoPatch;
  seedDemoSoftware: typeof seedDemoSoftware;
  seedDemoYear: typeof seedDemoYear;
  seedSchedule: typeof seedSchedule;
  sessions: typeof sessions;
  shifts: typeof shifts;
  sms: typeof sms;
  smsFlows: typeof smsFlows;
  smsTestFixtures: typeof smsTestFixtures;
  software: typeof software;
  songImport: typeof songImport;
  songs: typeof songs;
  splitSheets: typeof splitSheets;
  splitSignatures: typeof splitSignatures;
  stageDemo: typeof stageDemo;
  stripeConnect: typeof stripeConnect;
  studioBrain: typeof studioBrain;
  studioImport: typeof studioImport;
  studioManager: typeof studioManager;
  subaccountDeletion: typeof subaccountDeletion;
  testHarness: typeof testHarness;
  theme: typeof theme;
  timeclock: typeof timeclock;
  today: typeof today;
  twilioA2P: typeof twilioA2P;
  usage: typeof usage;
  visitors: typeof visitors;
  waitlist: typeof waitlist;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
