export const fps = 30;

export const pulsePromoScenes = [
  {
    id: 'rhythm-open',
    start: 0,
    duration: 120,
    timecode: '0:00-0:04',
    title: 'Every studio has a rhythm',
    voiceover: 'Every studio has a rhythm.',
    onScreenText: 'Every studio has a rhythm.',
    visual: 'Black void, thin glowing waveform, slow push-in, premium pulse glow.',
  },
  {
    id: 'chaos-build',
    start: 120,
    duration: 180,
    timecode: '0:04-0:10',
    title: 'Business falls out of sync',
    voiceover: 'But behind the music, the business can fall out of sync fast.',
    onScreenText: 'Out of sync.',
    visual: 'Unread DMs, calendar conflicts, invoice cards, file folders, revision notes drifting apart.',
  },
  {
    id: 'pain-points',
    start: 300,
    duration: 180,
    timecode: '0:10-0:16',
    title: 'Bookings files splits payments',
    voiceover: 'Bookings in text threads. Files in random folders. Splits in someone’s head. Payments waiting on a follow-up.',
    onScreenText: 'Bookings. Files. Splits. Payments.',
    visual: 'Kinetic typography slams in on beat with fragmented UI cards behind each keyword.',
  },
  {
    id: 'song-buried',
    start: 480,
    duration: 180,
    timecode: '0:16-0:22',
    title: 'The song gets buried',
    voiceover: 'And the song — the one thing everyone is working toward — gets buried under the chaos around it.',
    onScreenText: 'The song gets buried.',
    visual: 'Central song waveform becomes buried under stacked messages, invoices, sticky notes, and files.',
  },
  {
    id: 'pulse-reveal',
    start: 660,
    duration: 180,
    timecode: '0:22-0:28',
    title: 'Pulse changes the way the studio moves',
    voiceover: 'Pulse changes the way the studio moves.',
    onScreenText: 'Introducing Pulse',
    visual: 'Golden pulse line cuts through clutter; all elements snap into clean orbit around Pulse core.',
  },
  {
    id: 'studio operating system',
    start: 840,
    duration: 240,
    timecode: '0:28-0:36',
    title: 'Built around the song',
    voiceover: 'Pulse is the studio management CRM built around the song — from first idea to demo, session, mix, master, and release.',
    onScreenText: 'Built around the song.',
    visual: 'Large song record card opens; pipeline stages light up: Idea, Demo, Session, Mix, Master, Release.',
  },
  {
    id: 'workflow-orbit',
    start: 1080,
    duration: 240,
    timecode: '0:36-0:44',
    title: 'Everything connected to the track',
    voiceover: 'Every track becomes the center of its own workflow — with the people, sessions, files, splits, invoices, revisions, and deliverables connected in one place.',
    onScreenText: 'Everything connected to the track.',
    visual: 'Collaborator avatars, sessions, files, split sheet, invoice, revision, and deliverable cards orbit the song hub.',
  },
  {
    id: 'booking-calendar',
    start: 1320,
    duration: 240,
    timecode: '0:44-0:52',
    title: 'Bookings and calendar',
    voiceover: 'Book rooms, assign engineers, manage equipment, and let clients request sessions through a public booking flow that feeds the pipeline automatically.',
    onScreenText: 'Bookings that move straight into the pipeline.',
    visual: 'Calendar blocks assemble like a sequencer; booking request becomes confirmed session card.',
  },
  {
    id: 'pipeline-revenue',
    start: 1560,
    duration: 240,
    timecode: '0:52-1:00',
    title: 'Pipeline and revenue',
    voiceover: 'See every opportunity from inquiry to booked session, delivered project, upsell, license, and sync placement.',
    onScreenText: 'Inquiry → Booked → Delivered → Upsell',
    visual: 'Perspective Kanban board; cards glide through stages; licensing lane glows below.',
  },
  {
    id: 'payments',
    start: 1800,
    duration: 240,
    timecode: '1:00-1:08',
    title: 'Payments and reminders',
    voiceover: 'Keep money moving with deposits, milestones, invoices, overdue reminders, and Stripe-backed payment workflows.',
    onScreenText: 'Deposits. Milestones. Paid.',
    visual: 'Invoice card flips from Deposit Requested to Paid; revenue chart rises; reminder automation appears.',
  },
  {
    id: 'ai-agents',
    start: 2040,
    duration: 270,
    timecode: '1:08-1:17',
    title: 'AI operations',
    voiceover: 'Then bring in AI operations agents for booking, pipeline follow-up, collections, client success, and studio insights — with approvals when it matters.',
    onScreenText: 'AI operations. Human approval.',
    visual: 'Five AI agent cards appear with approval checkpoint glowing in Myind Sound yellow.',
  },
  {
    id: 'scale',
    start: 2310,
    duration: 240,
    timecode: '1:17-1:25',
    title: 'One studio or fifty',
    voiceover: 'Whether you run one room, one studio, or an agency network, Pulse gives your team one source of truth.',
    onScreenText: 'One studio or fifty. One system.',
    visual: 'Camera pulls back from one studio to multi-studio agency network with roles and scoped access.',
  },
  {
    id: 'end-card',
    start: 2550,
    duration: 150,
    timecode: '1:25-1:30',
    title: 'Run the studio around the song',
    voiceover: 'Pulse turns studio chaos into a system — so your team can focus on the music, the clients, and the next release.',
    onScreenText: 'Pulse. Run the studio around the song. Get early access.',
    visual: 'Waveform morphs into Pulse logo lockup; CTA button glows in #fbb03b.',
  },
] as const;
