#!/usr/bin/env python3
"""Render Lawrence's signature HTML files to the pixel-exact images used in email.

Gmail and Outlook remove the <style> block, CSS animation and positioning the
original signature files depend on, so the HTML itself breaks there. An image of
the finished design cannot. This script loads each original file in Chrome, waits
for the animation to finish, screenshots it at 2x, flattens it on the email card
colour (#111113) and writes convex/outreach/signatureImages.ts.

  pip install playwright pillow && playwright install chromium   # or use installed Chrome
  python3 scripts/outreach/render_signatures.py \
      --lawrence ~/Downloads/pulse_signature_lawrence_emailph.html \
      --roverto  ~/Downloads/pulse_signature_roverto_emailph.html

Re-run it whenever either source file changes. Needs network (the files load
their logo and photo from filesafe.space).
"""
import argparse, base64, io, pathlib, sys

CARD_BG = (17, 17, 19, 255)
OUT = pathlib.Path(__file__).resolve().parents[2] / "convex" / "outreach" / "signatureImages.ts"


def render(html_path: pathlib.Path) -> bytes:
    from playwright.sync_api import sync_playwright
    from PIL import Image

    fragment = html_path.read_text(encoding="utf-8")
    page_html = f'<!doctype html><html><head><meta charset="utf-8"></head><body style="margin:0;background:transparent">{fragment}</body></html>'
    with sync_playwright() as p:
        try:
            browser = p.chromium.launch(channel="chrome")
        except Exception:
            browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": 620, "height": 400}, device_scale_factor=2)
        page.set_content(page_html)
        page.wait_for_timeout(10000)  # typing, scan and sheen animations finish by ~8s
        png = page.locator(".pw").first.screenshot(omit_background=True)
        browser.close()
    im = Image.open(io.BytesIO(png)).convert("RGBA")
    flat = Image.new("RGBA", im.size, CARD_BG)
    flat.alpha_composite(im)
    out = io.BytesIO()
    flat.convert("RGB").save(out, format="JPEG", quality=92, subsampling=0, optimize=True)
    return out.getvalue()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lawrence", required=True, type=pathlib.Path)
    ap.add_argument("--roverto", required=True, type=pathlib.Path)
    args = ap.parse_args()
    lines = [
        "/* GENERATED by scripts/outreach/render_signatures.py from the original signature HTML files.",
        "   Do not edit by hand. Each string is a base64 JPEG of the finished design, 1120x380 (2x of 560x190). */",
        "",
    ]
    for const, path in (("LAWRENCE_SIGNATURE_JPEG_B64", args.lawrence), ("ROVERTO_SIGNATURE_JPEG_B64", args.roverto)):
        data = render(path)
        print(f"{const}: {len(data)} bytes", file=sys.stderr)
        lines.append(f'export const {const} = "{base64.b64encode(data).decode()}";')
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
