#!/usr/bin/env python3
"""Render the outreach signatures to the pixel-exact images used in email.

Gmail and Outlook remove the <style> block, CSS animation and positioning the
original signature HTML depends on, so the HTML itself breaks there. An image of
the finished design cannot. This script loads each signature in Chrome, waits
for the animation to finish, screenshots it at 2x, flattens it on the email card
colour (#111113) and writes convex/outreach/signatureImages.ts.

The source is the ORIGINAL_LAWRENCE / ORIGINAL_ROVERTO strings in
convex/outreach/signatures.ts (badge-free), so the picture always matches what
the "original" mode sends. Pass --lawrence / --roverto to render other files.

  pip install playwright pillow && playwright install chromium   # or use installed Chrome
  python3 scripts/outreach/render_signatures.py
  python3 scripts/outreach/render_signatures.py --browser /opt/pw-browsers/chromium-1194/chrome-linux/chrome

Re-run it whenever either signature changes. Needs network (the HTML loads its
logo and photo from filesafe.space).
"""
import argparse, base64, io, pathlib, sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from signature_sources import fragment, launch  # noqa: E402

CARD_BG = (17, 17, 19, 255)
OUT = pathlib.Path(__file__).resolve().parents[2] / "convex" / "outreach" / "signatureImages.ts"


def render(html: str, browser_path: "str | None") -> bytes:
    from playwright.sync_api import sync_playwright
    from PIL import Image

    page_html = f'<!doctype html><html><head><meta charset="utf-8"></head><body style="margin:0;background:transparent">{html}</body></html>'
    with sync_playwright() as p:
        browser = launch(p, browser_path)
        page = browser.new_page(viewport={"width": 620, "height": 400}, device_scale_factor=2)
        page.set_content(page_html)
        page.wait_for_load_state("networkidle")
        page.wait_for_timeout(10000)  # typing, scan and sheen animations finish by ~8s
        png = page.locator(".pw").first.screenshot(omit_background=True)
        browser.close()
    im = Image.open(io.BytesIO(png)).convert("RGBA")
    flat = Image.new("RGBA", im.size, CARD_BG)
    flat.alpha_composite(im)
    out = io.BytesIO()
    flat.convert("RGB").save(out, format="JPEG", quality=92, subsampling=0, optimize=True)
    return out.getvalue()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lawrence", type=pathlib.Path, help="HTML file; default: ORIGINAL_LAWRENCE in signatures.ts")
    ap.add_argument("--roverto", type=pathlib.Path, help="HTML file; default: ORIGINAL_ROVERTO in signatures.ts")
    ap.add_argument("--browser", help="path to a Chrome/Chromium binary")
    args = ap.parse_args()
    lines = [
        "/* GENERATED by scripts/outreach/render_signatures.py from the ORIGINAL_* signature HTML in signatures.ts.",
        "   Do not edit by hand. Each string is a base64 JPEG of the finished design, 840x286 (2x of 420x143). */",
        "",
    ]
    for const, key, path in (("LAWRENCE_SIGNATURE_JPEG_B64", "lawrence", args.lawrence), ("ROVERTO_SIGNATURE_JPEG_B64", "roverto", args.roverto)):
        data = render(fragment(key, path), args.browser)
        print(f"{const}: {len(data)} bytes", file=sys.stderr)
        lines.append(f'export const {const} = "{base64.b64encode(data).decode()}";')
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
